---
version: '3'
services:

  exchange_proxy:
    image: mikekonan/exchange-proxy:latest-amd64
    networks:
      customnetwork:
        ipv4_address: "172.25.0.2"
    restart: always
    container_name: exchange_proxy
    ports:
      - "127.0.0.1:8080:8080"


  freqtrade_download_1:
    image: freqtradeorg/freqtrade:stable
    networks:
      customnetwork:
        ipv4_address: "172.25.0.3"
    container_name: freqtrade_dry_download_1
    depends_on:
      - "exchange_proxy"
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data
      --new-pairs-days 1600
      --config user_data/kucoin_config.json
      -t 1m

  freqtrade_download_2:
    image: freqtradeorg/freqtrade:stable
    networks:
      customnetwork:
        ipv4_address: "172.25.0.4"
    container_name: freqtrade_dry_download_2
    depends_on:
      - "exchange_proxy"
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data
      --new-pairs-days 1600
      --config user_data/kucoin_config.json
      -t 5m 15m 30m 1h 2h 4h 6h 8h 12h 1d 1w

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.25.0.0/16
